version: 2.1

orbs:
  node: circleci/node@5.1.0
  rust: circleci/rust@1.6.0

jobs:
  build-linux-x64:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source
      - run: sudo apt-get install -y yasm
      - run: node build.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source
          paths:
            - ffmpeg
  build-linux-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source
      - run: sudo apt-get install -y yasm
      - run: node build.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source
          paths:
            - ffmpeg
  build-linux-macos:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install yasm
      - run: node build.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source
          paths:
            - ffmpeg
  build-linux-windows:
    build:
      docker:
        - image: mmozeiko/mingw-w64
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
        keys:
          - ffmpeg_source
      - run: node build.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source
          paths:
            - ffmpeg
workflows:
  build_ffmpeg:
    jobs:
      - build-linux-x64
      - build-linux-arm
      - build-linux-macos
