version: 2.1

orbs:
  node: circleci/node@5.1.0
  rust: circleci/rust@1.6.0
  win: circleci/windows@2.4.1

jobs:
  build-linux-x64-gnu:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source-linux-x64
      - run: sudo apt-get update
      - run: sudo apt-get install -y yasm clang
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: source "$HOME/.cargo/env"
      - run: node compile-ffmpeg.mjs
      - run: node generate-bindings.mjs
      - run: node zip.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-linux-x64
          paths:
            - ffmpeg
  build-linux-x64-musl:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - ffmpeg_source-linux-x64-musl
      - run: apk add yasm clang
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: node compile-ffmpeg.mjs
      - run: node generate-bindings.mjs
      - run: node zip.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-linux-x64-musl
          paths:
            - ffmpeg
  build-linux-arm-gnu:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source-linux-arm
      - run: sudo apt-get update
      - run: sudo apt-get install -y yasm clang
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: source "$HOME/.cargo/env"
      - run: node compile-ffmpeg.mjs
      - run: node generate-bindings.mjs
      - run: node zip.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-linux-arm
          paths:
            - ffmpeg
  build-linux-arm-musl:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source-linux-arm
      - run: sudo apt-get update
      - run: sudo apt-get install -y yasm clang musl
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: source "$HOME/.cargo/env"
      - run: node compile-ffmpeg.mjs musl
      - run: node generate-bindings.mjs
      - run: node zip.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-linux-arm
          paths:
            - ffmpeg
  build-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - ffmpeg_source-windows
      - run: choco install rust
      - run: choco install nodejs-lts
      - run: choco install rustup.install
      - run: rustup toolchain install stable-x86_64-pc-windows-gnu
      - run: rustup default stable-x86_64-pc-windows-gnu
      - run: node compile-ffmpeg.mjs windows
      - run: node generate-bindings.mjs
      - run: zip.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-windows
          paths:
            - ffmpeg

  build-macos:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source-macos
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install yasm
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: node compile-ffmpeg.mjs
      - run: node generate-bindings.mjs
      - run: node zip.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-macos
          paths:
            - ffmpeg

workflows:
  build_ffmpeg:
    jobs:
      - build-linux-x64-gnu
      - build-linux-arm-gnu
      - build-linux-x64-musl
      - build-linux-arm-musl
      - build-macos
      - build-windows
