version: 2.1

orbs:
  node: circleci/node@5.1.0
  rust: circleci/rust@1.6.0

jobs:
  build-linux-x64:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - run: sudo apt-get install -y yasm
      - run: node build.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
  build-linux-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - run: sudo apt-get install -y yasm
      - run: node build.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
  build-linux-macos:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - run: brew install yasm
      - run: node build.mjs
      - store_artifacts:
          path: ffmpeg.tar.gz
workflows:
  build_ffmpeg:
    jobs:
      - build-linux-x64
      - build-linux-arm
      - build-linux-macos
