on:
  push:
    branches:
      - main
  pull_request:
name: Build

env:
  FORCE_COLOR: 1
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          node build.mjs
      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg.zip
          path: ffmpeg.zip
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
